/**
 * @File Name          : HandlerContactTrigger.trigger
 * @Description        :  Trigger Assignment 22.Create a checkbox on contact object and Write a trigger to check that checkbox whenever a new contact is created.


 * @Group              : 
 * @Last Modified By   : Swapnil Thalal
 * @Last Modified On   : 19-03-22, 1:30:39 pm
* @Modification Log   : 
 **/

public with sharing class HandlerContactTrigger {
    
    public static Boolean isFirst = True;

}