//Find the Second Maximum From Array
/**
* @description       : 
* @author            : Minal Patil
* @group             : 
* @last modified on  : 02-08-2022
* @last modified by  : Minal Patil
**/
@isTest
public class SecondMaxArrayTest {
    
    @isTest
    public static void testMaxNo()
    {
       SecondMaxArray m = new SecondMaxArray();
        
        integer res = null;
        Test.startTest();
        res=m.SecondMax();
        Test.stopTest();
    }


}