/*
    Description : class is to display message


 * Filename: f:\GitWorkspace\Salesforce Template Application\force-app\main\default\classes\Calculator_Pooja.cls
 * Path: f:\GitWorkspace\Salesforce Template Application
 * Created Date: Wednesday, March 9th 2022, 5:47:29 pm
 * Author: Pooja Kudale
 * 
 * Copyright (c) 2022 Your Company
 */

public with sharing class Test_Pooja
{
    //method to display greeting message
    public String display(String msg)
    {
        return msg;
    }
}