/**
* @description       : Test class for Sort all the elements
* @author            : Neha Athawale
* @group             : 
* @last modified on  : 09-02-2022
* @last modified by  : Neha Athawale
**/
@isTest
public class TestSortEle {

    @isTest
    public static void Method()
    {
        SortEle s=new SortEle();
        Test.startTest();
        integer result = s.sortMethod();
        Test.stopTest();
    }
}