/**
* @description       :test class for SortArray class
* @author            : Snehal Pawar
* @group             : 
* @last modified on  : 02-09-2022
* @last modified by  : Snehal Pawar
**/
@isTest
public class TestSortArray {
@isTest
    public static void testSortArray()
    {
        SortArray m=new SortArray();
     
        integer res=null;
        Test.startTest();
         res = m.sortArray();
        Test.stopTest();

    }
}