//Find the third Maximum From Array 
/**
* @description       : 
* @author            : Minal Patil
* @group             : 
* @last modified on  : 02-08-2022
* @last modified by  : Minal Patil
**/
@isTest
public class ThirdMaxArrayTest {
    
     @isTest
    public static void testMaxNo()
    {
       ThirdMaxArray m = new ThirdMaxArray();
        
        integer res = null;
        Test.startTest();
        res=m.ThirdMax();
        Test.stopTest();
    }

}